---
- name: Install development packages
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name:
      - awscli
      - docker-completion
      - docker-compose-completion
      - git
      - jq
      - rsync
      - tig
      - vagrant-completion
    state: present

- name: Install development applications
  become: true
  become_user: '{{ user_name }}'
  homebrew_cask:
    name:
      - devdocs
      - docker
      - vagrant
      - virtualbox
      - wireshark
    state: present

- import_tasks: bash.yml
- import_tasks: python.yml
- import_tasks: node.yml
